# Generated by Django 5.0.4 on 2025-01-16 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.CharField(help_text='School ID or Employee ID', max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('time_in_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-time_in_date'],
            },
        ),
    ]
